version: '3'
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}
    image: ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSGRES_HOST=${DB_HOST}
      - DEBUG=${DEBUG}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    env_file:
      - .env
volumes:
  data:
