# Generated by Django 4.2.9 on 2024-03-23 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
        ('task_steps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstep',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_steps', to='task.task'),
        ),
    ]
