# Generated by Django 4.2.9 on 2024-03-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_steps', '0004_alter_taskstep_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskstep',
            name='output',
        ),
        migrations.AlterField(
            model_name='taskstep',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('ON_PROGRESS', 'ON_PROGRESS'), ('DONE', 'DONE')], default='NOT_STARTED', max_length=16),
        ),
    ]
