# Generated by Django 4.2.9 on 2024-04-21 11:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task_steps', '0005_remove_taskstep_output_alter_taskstep_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('end_datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('task_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timelines', to='task_steps.taskstep')),
            ],
        ),
    ]
