# Generated by Django 4.2.9 on 2024-04-22 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_timeline_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='event',
        ),
    ]
