# Generated by Django 4.2.9 on 2024-04-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='midtrans_id',
            new_name='midtrans_transaction_id',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='payment_destination',
            new_name='payment_merchant',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payment_channel',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_details',
        ),
        migrations.AddField(
            model_name='transaction',
            name='expiry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='midtrans_token',
            field=models.CharField(db_index=True, max_length=1024, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
