# Generated by Django 4.2.9 on 2024-04-29 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_midtrans_id_transaction_midtrans_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-checkout_time']},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='checkout_date',
            new_name='checkout_time',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='paid_at_date',
            new_name='paid_at_time',
        ),
    ]
