# Generated by Django 4.2.9 on 2024-05-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_transaction_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='order_id',
            field=models.UUIDField(db_index=True, unique=True),
        ),
    ]
