# Generated by Django 4.2.9 on 2024-05-06 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_alter_transaction_midtrans_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='paid_at_time',
        ),
    ]
