# Generated by Django 5.0.2 on 2024-02-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=20)),
                ('objective', models.TextField()),
                ('attendees', models.IntegerField()),
                ('thmee', models.TextField()),
                ('services', models.TextField()),
            ],
        ),
    ]
