# Generated by Django 4.2.9 on 2024-03-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recommend_vendor',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='recommend_venue',
            field=models.BooleanField(default=True),
        ),
    ]
