# Generated by Django 4.2.9 on 2024-05-04 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_appuser_subscription_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='subscription_end_date',
        ),
    ]
