# Generated by Django 4.2.9 on 2024-05-22 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_appuser_subscription_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='real_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='real_username',
            field=models.TextField(null=True),
        ),
    ]
