# Generated by Django 4.2.9 on 2024-05-24 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_appuser_real_email_appuser_real_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='real_email',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='real_username',
        ),
    ]
