# Generated by Django 4.2.9 on 2024-03-05 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0003_alter_venue_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='PhotoVenue',
        ),
    ]
