# Generated by Django 4.2.9 on 2024-02-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0005_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
