# Generated by Django 4.2.9 on 2024-04-21 12:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0003_event_recommend_vendor_event_recommend_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rundown',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('description', models.TextField()),
                ('rundown_order', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rundown', to='event.event')),
            ],
        ),
    ]
