# Generated by Django 4.2.9 on 2024-04-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rundown', '0002_alter_rundown_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rundown',
            name='rundown_order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
