# Generated by Django 4.2.9 on 2024-03-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendationhistory",
            name="keyword",
            field=models.TextField(default="[]"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recommendationhistory",
            name="list",
            field=models.TextField(default="[]"),
            preserve_default=False,
        ),
    ]
