# Generated by Django 4.2.9 on 2024-03-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0002_recommendationhistory_keyword_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendationhistory",
            name="type",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
