# Generated by Django 4.2.9 on 2024-03-29 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_event_user"),
        ("ai", "0003_recommendationhistory_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendationhistory",
            name="event",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="event.event"
            ),
        ),
    ]
