name: Django App Deployment

on:
  push:
    branches:
      - staging
  workflow_run:
    workflows: ["Django CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get remove containerd.io
          sudo apt-get install -y docker.io
          sudo apt-get install -y docker-compose

      - name: Build and push Docker image
        run: |
          docker build -t revelio-be-image .
          docker tag revelio-be-image:latest 104.154.120.50/revelio-be-image:latest
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin 104.154.120.50
          docker push 104.154.120.50/revelio-be-image:latest

      - name: SSH into VM and deploy
        uses: appleboy/ssh-action@master
        with:
          host: 104.154.120.50
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /path/to/your/django/app
            docker-compose pull
            docker-compose down
            docker-compose up -d

